preset: laravel

enabled:

disabled:
  - length_ordered_imports
  - no_unused_imports
  - phpdoc_summary
  - phpdoc_var_without_name
  - post_increment

finder:
  exclude:
    - "tests"
    - "storage"
    - "vendor"