language: php

php:
  - 7.0

before_script:
  - cp .env.example .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:keys

script:
  - composer run test-ci
  - composer run lint

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false