language: php

php:
  - 7.3
services:
  - postgresql
before_script:
  - cp .env.example .env
  - psql -c 'create database utnianos_local;' -U postgres
  - psql -c 'create database utnianos_local_test;' -U postgres
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan jwt:secret

script:
  - composer run test-ci
  - composer run lint

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
